Moosh/Command/Generic/Plugin/PluginUnInstall.php

Hi Tomasz,
I needed to remove some redundant plugins from my Moodle servers, so I developed a new plugin: 
moosh plugin-uninstall module_name
It simply removes the plugin from the DB and from the disk, And also It can remove plugins that have no folder on the disk and have some redundant data inside DB tables.
If you do not have write permissions on the plugins' folder it will prompt you with the proper CL that will gain the right permissions and then you are asked to run the command again.
Syntax:
moosh plugin-uninstall theme_elegance

New plugin: plugin-uninstall module_name

---

Moosh/Command/Moodle26/Admin/AdminLogin.php
Moosh/MooshCommand.php
moosh.php

the "admin-login" command logins the "admin" user, creates a moodle session, and returns a {cookie name} - {cookie value} pair. It's possible then to use the cookie to download a Moodle page that requires authentication, such as the notification page

add admin-login command

---

Moosh/Command/Moodle23/Course/CourseBackup.php

Sometimes a user would like to backup a course and restore in a new semester/quarter without user info or submissions. This commit add the --template flag to provide for that.

Add option for template course backups

---

Moosh/Command/Moodle23/Course/CourseRestore.php

In the configuration of Moodle, $CFG->tempdir is by default set to
$CFG->dataroot / temp. When set to another value, `moosh.php course-restore`
will crash because it hard-codes the default path, while Moodle uses the
configured one.

CourseRestore should use 'tempdir' instead of hardcoding the path

---

Moosh/Command/Moodle23/Config/ConfigSet.php
moosh.php

config-get uses the plugin names 'moodle' and 'core' to refer to the mdl_config table, and all other plugin names to refer to the mdl_config_plugins table. config-set does not behave the same way - it ONLY treates the absense of a plugin as referring to the mdl_config table. This results in inconsistent behaviour between config-get and config-set which can be very confusing.
The addition of a simple if statement removes this confusion.

150618 make config set more robust

---

Moosh/Command/Generic/Plugin/PluginUnInstall.php

Some plugins does not clean up gracefully - repositories, old assignments, old themes.
And so, removing their folders does not clean the Moodle database tables and we can use moosh plugin-uninstall to remove redundant leftovers. 
Except... when the plugin folder is missing, moosh breaks/stops and as to create one with the proper permissions, just so he (Moodle) could later delete it.
So, I patched the "plugin-uninstall" code so it skips the folder permission check if it does not exists in the first place (was removed at some point).
Tested it several times on various types of plugins (as I needed to clean up some Moodle servers I manage), And it seems ok.
Please review and consider adding to your code.
Nadav :-)

plugin-uninstall - Skip missing folder if one does not exists

---

Moosh/Command/Generic/Plugin/PluginInstall.php

This is an attempt at fixing #114.
I think we should consider moving the plugin-install command into Moodle20 or Moodle26 as the method for determining plugin installation locations was introduced in 2.0 and changed in 2.6.
This command also makes use of /lib/upgradelib.php which was not introduced until 2.0. Which means it won't work in 1.9.

Add plugin installation location logic

---

Moosh/Command/Moodle27/Dev/GenerateLocal.php

Works fine under 2.7 - should live here

Moving 'generate-local' command to moodle 2.7

---

Moosh/Command/Moodle23/Dev/GenerateModule.php

renaming of backup files failed due to missing '.class' in filename

fixing bug in generate-module command

---

Moosh/Command/Moodle29/Course/CourseRestore.php

The current version off CourseRestore.php resides in Moodle23. It has no feature to overwrite an existing course. Instead the content of the backup is added to the current content of the existing course. This new CourseRestore.php has a new option -o that works together with -e. If used this new option deletes the course content of the existing course before adding the content of the backup file.
This is my first activity in code on GitHub - so please forgive me if I am doing something wrong :-)

Create new file CourseRestore.php in Moodle29

---

Moosh/Command/Generic/Tools/ToolsCodeCheck.php

Even though the parameter is available in the command, it was not being passed to the PHP_CodeSniffer constructor

Fixed interactive mode option in code-check command

---

Moosh/Command/Generic/Apache/ApacheParsePerfLog.php

Regexp now searches for timestamp in square brackets. Allows to parse different timestamps besides default one.
[28-Jul-2016 13:54:36 Europe/Paris]
-----
Result of date_parse
php -r 'print_r(date_parse("28-Jul-2016 13:54:36 Europe/Paris"));'  
Array
(
[year] => 2016
[month] => 7
[day] => 28
[hour] => 13
[minute] => 54
[second] => 36
[fraction] => 0
[warning_count] => 0
[warnings] => Array
(
)
[error_count] => 0
[errors] => Array
(
)
[is_localtime] => 1
[zone_type] => 3
[tz_id] => Europe/Paris
)

Fix to apache-parse-perflog. Extending date timestamp regexp search

---

composer.json

Composer will determine version based on git tag or git branches instead of all the time hardcoded same version (0.18).

Remove hardcoded version from composer

---

Moosh/Command/Generic/User/ImportUserPictures.php
Moosh/Command/Moodle22/User/ImportUserPictures.php
www/commands/index.md

Hello there!
Moodle admin interface already supports importing of user profile pictures. However, a user might experience various problems when uploading big payloads over the wire for relatively big imports (1000+ users) and photos in high resolution. The process might be interrupted by php-fpm / php / webserver timeouts or memory limits.
CLI interface provides more reliable and faster way to accomplish mass import.
Tests are not implemented though. I've seen SH scripts for testing purposes, however I'm not really familiar how things work in this repo. Could you please point me in the right direction?
Cheers

Added command to support importing of user profile pictures.

---

Moosh/Command/Moodle23/Config/MaintenanceOff.php

So it's always keep empty. We need this because we use the two different maintenance modes. One using the climaintenance.template.html file and one using the UX-mode with the maintenance_message.

 Reset maintenance_message after maintenance mode

---

Moosh/Command/Moodle23/File/FileList.php
www/commands/index.md

Hi Tomasz,
Please review and consider adding a new improvement onto the filelist command, that
Check/Remove existing DB file entries which are missing from the file system.
It help solves some inconsistencies we had between the files listed on the {files} DB table and the files listed (or missing) on the file system. (you can usually see those warring on the automatic cron backups report)
Nadav

Check/Remove existing DB files which are missing from the file system

---

Moosh/Command/Moodle26/Course/CourseList.php

Avoid this error:
Default exception handler: Error reading from database Debug: ORA-00920: invalid relational operator
SELECT c.id,c.category,c.shortname,c.fullname,c.visible FROM mdl_course c WHERE '1'
Error code: dmlreadexception
* line 479 of /lib/dml/moodle_database.php: dml_read_exception thrown
* line 277 of /lib/dml/oci_native_moodle_database.php: call to moodle_database->query_end()
* line 1245 of /lib/dml/oci_native_moodle_database.php: call to oci_native_moodle_database->query_end()
* line 88 of /moosh/Moosh/Command/Moodle26/Course/CourseList.php: call to oci_native_moodle_database->get_records_sql()
* line 289 of /moosh/moosh.php: call to Moosh\Command\Moodle26\Course\CourseList->execute()

Fix WHERE to work on Oracle DB

---

Moosh/Command/Moodle23/Config/MaintenanceOff.php

There was an typo in the set_config('maintenance_mesage', ''); line

Fix typo in maintenance-off cmd

---

Moosh/Command/Moodle23/Sql/SqlDump.php

SqlCli command supports mariadb but SqlDump does not. This pull request adds mariadb support to SqlDump.

Add mariadb support to SqlDump command.

---

Moosh/Command/Moodle23/Course/CourseCreate.php
www/commands/index.md

The patch forces course-create to follow the default course config setting for numsections, as master does already for format, if a new numsections option is not used.
Using the new option, you can specify other numsections values.
I think this is desirable, if you are using course-create on a production site.
The index.md patch documents in addition the format option, which behaves similarly.

add numsections option to course-create

---

Moosh/Command/Moodle26/Activity/ActivityAdd.php
tests/commands/activity-add.sh
www/commands/index.md

Only long options (--option=value) are supported.
As requested in, https://moodle.org/mod/forum/discuss.php?d=368091

Parses activity-specific options passed in, for example, --o "--intro=\"2 emails\" --course=33 --subnet=192.168.2.2"

---

Moosh/Command/Moodle26/Category/CategoryImport.php

Command "category-import" only import category names and hierarchy but idnumber is included in the XML file obtained with "category-export".

Add idnumber when importing categories

---

Moosh/Command/Moodle23/Course/CourseEnrol.php
Moosh/Command/Moodle23/Course/CourseEnrolByName.php

My first attempt at contributing to any git repository so hopefully I am doing this correctly!
My organization uses moosh to manage our Moodle and we will soon be needing to enrol users with start and end dates on their enrollments.  Moosh is not capable of doing this so I thought I could add it.  
I thought that having the ability to specify both a duration or an end time would be helpful so I have built in the ability for either option.

update enrol functions to include start/end dates

---

Moosh/Command/Moodle26/Activity/ActivityAdd.php

edit_module_post_actions, called from add_moduleinfo, called from create_instance sets up a grade item's categoryid from a 'gradecat' field in the moduleinfo record.
Having a grade category is a useful property for most (all?) activities on a production site.  And, omission of the option will just result in the same behavior as before, the grade category being Uncategorized.

gradecat grade_category id option for activity-add

---

Moosh/Command/Moodle26/Activity/ActivityAdd.php

GetOptionKit does not support underscore in getOptionName. 
Some activity setting options have underscores, eg quiz's safeexambrowser_allowedkeys
This patch copies the regex from getOptionName into a same-named function in ActivityAdd.php and adds the underscore.

underscore in option name in activity-add

---

Moosh/Command/Moodle23/Course/CourseDelete.php

The current output (from Moodle code) shows output like:
++ Deleted - Completion tracking ++
++ Deleted - Grades, Items, Categories ++
... 
but has no indication of which course this refers to.

Output which course will be deleted

---

Moosh/Command/Moodle29/Course/CourseRestore.php
Moosh/Command/Moodle33/Course/CourseRestore.php

The course restore precheck can generate warnings and errors.
Many of the warnings that get generated do not impede course restores. I
added a flag that allows for ignoring course-restore warnings.
Here is an example of a warning I was experiencing:
```
'warnings' =>
array(5) {
[0] =>
string(148) "The questions category "CNC New: Turning", originally at system/course category context in backup file, will be created at course context by restore"
[1] =>
string(193) "The questions category "CNC Turning Technology with BenchTurn 7000 (Imperial/Virtual)", originally at system/course category context in backup file, will be created at course context by restore"
[2] =>
string(195) "The questions category "CNC Milling Technology with the ProMill 8000 (Imperial/Virtual)", originally at …
```

Allow for ignoring warnings on course-restore

---

Moosh/Command/Moodle23/File/FileUpload.php

Getting this error when executing `moosh file-upload --filename=169.mbz /app/moodledata/backup.mdz`
```
Notice: Undefined variable: filepath in /app/vendor/tmuras/moosh/Moosh/Command/Moodle23/File/FileUpload.php on line 71
Default exception handler: Cannot read file. Either the file does not exist or there is a permission problem. Debug:
Error code: storedfilecannotread```
Looking at the code in `FileUpload.php` $filepath variable is only set when the specified file does not start with a leading forward slash. In addition, $arguments[0] is used to reference the filepath throughout the code so suggest its more consistent to just use that throughout.

filepath variable is not always set

---

Moosh/Command/Moodle27/Theme/SettingsExport.php

createElement only escapes < and > for some reason.
https://www.php.net/manual/en/domdocument.createelement.php

fixes #265, encode ampersands when storing to xml

---

includes/functions.php

In new moodle version /lib/clilib.php,  have the function cli_problem($text) already declared. 
Same is declared in Moosh includes/functions.php,, resulting in 
Fatal error: Cannot redeclare cli_problem() (previously declared in /usr/share/moosh/includes/functions.php:109)

Cannot redeclare cli_problem error

---

Moosh/Command/Moodle23/Course/GradebookExport.php
www/commands/index.md

Writing to a file is not implemented. Use shell redirection.
Options similar to the settings available when exporting via a browser are supported.
I considered a 'fields' options to restrict fields exported, but you can do that with the grade_export_userprofilefields setting in the 
Grades--General Settings window in Site administration.

gradebook-export

---

Moosh/Command/Moodle23/GradeItem/GradeItemCreate.php
www/commands/index.md

From  the documentation:
Creates grade items, with command-line options and courseid, gradecategoryid arguments.
Example:
moosh gradeitem-create --itemname=Boost --grademax=3 --calculation='=max(3, ##gi5075##)' -o '--aggregationcoef=1' 37 527

gradeitem-create

---

Moosh/Command/Moodle26/Question/QuestionImport.php

Fixes Class 'Moosh\Command\Moodle26\Question\question_edit_contexts' not found

#252 Fix missing namespacing

---

Moosh/Command/Moodle23/Activity/ActivityConfigSet.php
www/commands/index.md

Does the same kind of thing as course-config-set, setting fields in the database, but on activities (of a given type). Also, it is restrictable to activities in a section.

activity-config-set command

---

Moosh/Command/Moodle35/Category/CategoryList.php

Fixes #250 
Allow selecting tabbed or CSV output in category-list. The default output is exactly as at present, space-padded to 15 characters, with fields running together when more than 15 characters.

Allow tabbed and CSV output in category-list

---

Moosh/Command/Moodle23/Sql/SqlCli.php
www/commands/index.md

cockroachdb uses the same wire protocol as postgres.
This adds support for the CLI

feat: add support for cockroachdb

---

Moosh/Command/Moodle36/Category/CategoryResortCourses.php

Add the -r / --recursive flag to CategoryResortCourses.php. The initial code by  @benyovszky  only sorts the courses in a single category. This flag will sort allow the user to sort this category's courses,
and continue recursively. 
I took most of the code from /course/management.php
I believe this is an enhancement re: #287

Add recursive option on CategoryResortCourses.php re: #287

---

composer.json

When the word TEMPLATE is all in uppercase, composer was generating a warning:
Deprecation warning: require.jamiepratt/moodle-qtype_TEMPLATE is invalid, it should not contain uppercase characters. Please use jamiepratt/moodle-qtype_template instead. Make sure you fix this as Composer 2.0 will error.
Now that Composer 2.0 is out, it causes an error:
[RuntimeException]
require.jamiepratt/moodle-qtype_TEMPLATE is invalid, it should not contain uppercase characters. Please use jamiepratt/moodle-qtype_template instead.  
Now changed to lowercase.

Fixed require.jamiepratt/moodle-qtype_TEMPLATE is invalid

---

Moosh/Command/Generic/Download/DownloadMoodle.php

This addresses Issue #324. It appears that the naming convention changed for how Moodle stores files to be downloaded. I was not involved writing this initial code, but it's clear that the current code gives a 404 error.
Before, if the version wasn't given as an option, it downloaded the most recent release. That file was stored like `moodle-latest-38.tgz`
As of now (3.9), it looks like `moodle-latest-39.tgz` does not exist, but `moodle-3.9.tgz` is indeed the latest version.
Also made some change to this code if a point release wasn't given, it redirects to `moodle-latest-majorminor.tgz` that seems to work. I don't know how this worked before - I might be missing something.
Also made a few miscellaneous updates to help match Moodle code style guidelines.

Fix download-moodle - Issue #324

---

www/index.md

This PR fixes a couple of URLs that have to be copy-pasted instead of just clicked.

Fixed URLs to markdown format

---

Moosh/Command/Moodle23/Course/SectionConfigSet.php
www/commands/index.md

I thought it was important to use core_course's course_update_section because it triggers the \core\event\course_section_updated event, which
observers may be waiting for.
It seems silly to call $DB->get_field just after course_update_section has called $DB->update_record, but course_update_section doesn't have any mechanism for reporting failure and having error messages for the command which are the same as those for course-config-set and activity-config-set seemed desirable.

course-config-set: updates field in {course_sections} table

---

Moosh/Command/Moodle36/Cohort/CohortEnrolfile.php
www/_site/commands/index.html
www/commands/index.md

Given a CSV, will enroll all users into corresponding cohorts
Don't know if there's any appetite for this command, but I know I could use it from time to time to manage cohorts. Understandable if it's just me.
Also, if it should not be a separate command, but instead be folded into `cohort-enrol`, let me know and I'll work on that instead.
Also attempted to add documentation into web and index.md for the command

New feature: cohort-enrolfile

---

Moosh/Command/Moodle28/Module/ModuleCopy.php
www/_site/commands/index.html
www/commands/index.md

This feature allows the user to copy a module from one course to another. It is based heavily off of `duplicate_module()` in `course/lib.php`.
**Required arguments:** `moduleid` `courseid`
**Available options:** `name` of new module and `section` of destination course, 0 if not given or incorrect.
* Currently resets all access restrictions, if copied to a different course than the origin course. Future work would be to keep date/grade/user profile restrictions, and drop group/activity completion restrictions.

Implement new feature: module-copy

---

Moosh/Command/Moodle23/User/UserCreate.php
Moosh/Command/Moodle23/User/UserDelete.php
Moosh/Command/Moodle23/User/UserList.php
Moosh/Command/Moodle23/User/UserMod.php
Moosh/Command/Moodle25/User/UserMod.php
Moosh/Command/Moodle31/User/UserMod.php
Moosh/MooshCommand.php
moosh.php

It is useful to create a new user via moosh, even there is currently no admin (mdl_users might be completely empty)
The commands work already in that way, just a new bootstrap level is introduced to allow the user commands without an admin user

#358 Allow creating users without an existing admin

---

Moosh/Command/Moodle27/Theme/SettingsExport.php

Minor fix for problem when exporting relative urls like /mod/blah/view.php?id=3 in theme settings.

Fixes #302 theme settings export of relative urls

---

composer.json
composer.lock

Updates git info for the `moodle-tool_pluginskel` dependency so it installs correctly.
Closes https://github.com/tmuras/moosh/issues/367

update reference to moodle-tool_pluginskel

---

Moosh/Command/Moodle39/User/UserMod.php

This is a very naive implementation of this feature. I just looked at the Moodle database model [1] and did not see a problem at first glance. If this is a very bad idea because of moodle implementation details please feel free to correct me.
[1] https://www.examulator.com/er/output/tables/user.html

allow renaming of user with user-mod

---

Moosh/Command/Moodle39/Config/ConfigPluginimport.php

It was observed, that it was not possible to refer to the config file
to be imported by config-plugin-import with an absolute path.
The existing resolution routine, that converted a relative path to an
absolute path, did not handle this correctly. Instead of rolling our
own routine, this PR replaces it with the built-in function realpath,
which resolves the provided path to a fully qualified one.

Simplify/fix resolving of inputfile for config-plugin-import

---

Moosh/Command/Moodle39/Config/ConfigPluginexport.php

When running config-plugin-export for a fresh installation of moodle
3.11 errors about unterminated entity references were reported:
```
mmatblsi@ITMC-DEV-N01:/var/www/moodle$ sudo sudo -u www-data moosh config-plugin-export -o /tmp/config atto_equation
PHP Warning:  DOMDocument::createElement(): unterminated entity reference  a_2 \ a_3 & a_4 \end{matrix} \right|
\frac{a}{b+c}
\vec{a}
\binom {a} {b}
{a \brack b}
{a \brace b} in /usr/local/moosh-2022040300/Moosh/Command/Moodle39/Config/ConfigPluginexport.php on line 143
Warning: DOMDocument::createElement(): unterminated entity reference  a_2 \ a_3 & a_4 \end{matrix} \right|
\frac{a}{b+c}
\vec{a}
\binom {a} {b}
{a \brack b}
{a \brace b} in /usr/local/moosh-2022040300/Moosh/Command/Moodle39/Config/ConfigPluginexport.php on line 143
Config …
```

Ensure configuration data is correctly XML escaped

---

Moosh/Command/Moodle33/Role/RoleExport.php
Moosh/Command/Moodle33/Role/RoleImport/core_role_define_role_table_advanced_extended.php
Moosh/Command/Moodle33/Role/Roleimport.php
www/commands/index.md

Export role data, including permissions, role overrides, allow view settings and other related data.
Example 1: Export specific role data to a an output XML file.
moosh role-export -f target_file.xml ROLENAME
Example 2: Export specific role data, generate output XML export and print to stdout.
moosh role-export ROLENAME
Example 3: Format XML with whitespaces (pretty format) and output XML contents to stdout.
moosh role-export --pretty ROLENAME
Import role data from an XML file that was produced either by role-export command or Moodle permissions UI. 
Example 1: Import role from a specific XML file.
moosh role-import -f source_file.xml
Example 2: Import role by reading XML data from STDIN.
moosh role-import --stdin < source_file.xml
You can either load XML data from a file or from STDIN. …

Add role import-export command

---

Moosh/Command/Moodle39/Role/RoleReset.php

Fix typo to include role allow_view settings when resetting the role settings.

Fix role reset command to include allow_view role settings

---

Moosh/Command/Moodle39/User/UserOnline.php
www/commands/index.md

Display currently online users in a simple table. In a contrast to TOP command this command uses Fetcher API and queries user table instead of standard log store.
Available options:
| Option           | Description                                                   |
|------------------|---------------------------------------------------------------|
| -t, --time       | Show users online in last N seconds. Default 15 sec.          |
| -l, --limit      | Show maximum number of users. If empty all users are fetched. |
| -e, --hideheader | Print header with table column names.                         |
Use linux "watch" command to refresh screen periodically.
Example: Show online users in last 5 minutes and refresh list every 5 seconds.
watch moosh user-online -t 300

Add user online command

---

Moosh/Command/Moodle39/Report/DataStats.php

Fix small typo in SQL query which references table identifier without using a proper parameterised syntax.
The problem occurs on Moodle setups that use table prefix different than default `mdl_`.

Fix SQL query which references table identifier without using a proper parameterised syntax

---

Moosh/Command/Generic/Plugin/PluginDownload.php
Moosh/Command/Generic/Plugin/PluginInstall.php
Moosh/Command/Generic/Plugin/PluginList.php
www/commands/index.md

Add new command line option to specify proxy server to be used while communicating with Moodle plugin repository.
Instead of command line option a user may define environment variable http_proxy or HTTP_PROXY.

Add proxy support to a group of plugin commands

---

Moosh/Command/Moodle39/Config/ConfigPluginimport.php

Explained in this issue: <https://github.com/tmuras/moosh/issues/456>
`$this->inputfilepath` contains the entire path
while `$setting->getAttribute('file')` contains the hash

fix: config-plugin-import builds additional file paths incorrectly

---

Moosh/Command/Moodle33/Role/Roleimport.php

Quick fix to allow importing roles without archetypes

Allow importing roles with no archetypes

---

Moosh/Command/Moodle39/Course/CourseReset.php

Hi
Course_reset command set wrong dates in activities
when start and/or end dates are set in these ones.
See sample in this issue : https://github.com/tmuras/moosh/issues/474
Thanks

Wrong activities dates when use course_reset command

---

Moosh/Command/Generic/Plugin/PluginInstall.php

Some plugins .zip file decompress in non standard directory (e.g. : zip file for atto_multilang2 decompresses into moodle-atto_multilang2-<version>; mod_hvp decompresses into 2 dir "hvp" and "__MACOSX")
I managed this by unpacking the zip file into the moosh tempdir, and then moving it to the right path with the correct dir name.
Tell me if there is anything wrong with these changes

Accounting for non standard plugin packages when using plugin-install

---

Moosh/Command/Moodle39/Cohort/CohortEnrol.php
Moosh/Command/Moodle39/Cohort/CohortUnSync.php
Moosh/Command/Moodle39/Course/CourseAssignRole.php
Moosh/Command/Moodle39/Course/CourseDisableEnrolment.php
Moosh/Command/Moodle39/Course/CourseEnableguest.php
Moosh/Command/Moodle39/Course/CourseEnableselfenrol.php
Moosh/Command/Moodle39/Course/CourseReorder.php
Moosh/Command/Moodle39/Course/CourseUnassignRole.php
Moosh/Command/Moodle39/Course/CourseUnenrol.php
Moosh/Command/Moodle39/User/UserList.php

Would you consider merging these changes?
New commands:
- course-assign-role
- course-disableenrolment
- course-enableguest
- course-reorder
- course-unassign-role
Changes:
- Add a couple of 'break' to course-enableselfenrol to stop after finding 1st matching enrolment instance.
- Add a --plugin option to course-unenrol to match enrolment plugin type.
- Add a --course-enrol-plugin option to course-enrol-plugin to match enrolment plugin type.

New commands, couple of new features

---

composer.json
composer.lock

Upgrade corneltek/getoptionkit to commit aab2728de80175217cab0d7a4d078c3eb907e2c0 to avoid several deprecation.
Seems that php 8.1 deprecations were resolved from this commit : https://github.com/c9s/GetOptionKit/commit/1121ee17f304cd7e2d8d2b818df86b6af5f07485

fix 448 - corneltek/getoptionkit upgrade to commit aab2728d

---

Moosh/Command/Moodle39/Info/ChkDataDir.php

declare $filelist in class to avoid deprecated on dynamic property message
resolve issue https://github.com/tmuras/moosh/issues/482 (Creation of dynamic property in ChkDataDir.php)

fix 482 - declare dynamic property filelist

---

Moosh/Command/Moodle39/Course/CourseInfo.php

Fixes #485.
Three properties weren't declared:
- $enrolledtotal
- $logsnumber
- $data
So I declared them as private properties to remove the deprecated messages.

MOOSH485 - Fix Dynamic Properties - CourseInfo.php

---

Moosh/Command/Generic/Plugin/PluginHideShow.php
Moosh/Command/Generic/Request/RequestSelect.php
Moosh/Command/Moodle39/Cache/CacheSet.php
Moosh/Command/Moodle39/Category/CategoryMoveCoursesFromCategoryToAnother.php
Moosh/Command/Moodle39/Cohort/CohortDelete.php
Moosh/Command/Moodle39/Context/ContextFreeze.php
Moosh/Command/Moodle39/Course/CourseEnrolChangeStatus.php
Moosh/Command/Moodle39/Dashboard/DashboardResetAll.php
Moosh/Command/Moodle39/Task/TaskSchedule.php
Moosh/Command/Moodle39/Webservice/WebserviceInstall.php
Moosh/Command/Moodle41/Cache/CacheStoreClear.php

Hello,
First of all, thanks a lot for this very usefull Moosh tool.
It help us in our everyday work.
Would you be interested in adding this few commands I made for my University?
- plugin-hideshow -> hide or show a plugin
- request-select -> A select command with a csv output
- cache-set -> This command enable to attribute cache to specific cache definition
- category-move-courses-from-category-to-another -> Move all courses of a category into an other one
- cohort-delete -> Delete a cohort
- context-freeze -> Freeze a context
- course-enrol-change-status -> Change enrol status in a course
- dashboard-reset-all -> Reset all deashboards
- task-schedule -> Schedule Moodle task
- webservice-install -> Install a webservice
- cache-store-clear -> Clear a specific cache
Regards
Céline - …

New commands proposal

---

Moosh/Command/Moodle39/Dev/GenerateFiles.php

Fixes #494 - use the `random_bytes()` present in currently supported PHP version instead.

MSH494 - Replace deprecated random_bytes_emulate()

---

Moosh/Command/Moodle39/Course/CourseEnrolChangeStatus.php
Moosh/Command/Moodle39/Course/CourseList.php
www/commands/index.md

correction proposal of #490 
Regards
Céline

[tmuras/moosh#490] correct a having for postgres

---

Moosh/Command/Moodle39/Cohort/CohortEnrol.php

If a cohort-enrol -c XX "cohortname" is run and the id for "cohortname" matches another `customint1` in the `mdl_enrol` table for that course, it will state that the cohort is already enrolled when it's not. This verifies that the `customint1` is for the `cohort` enrol type.
The fix was just to add `'enrol' => 'cohort'` to make sure that we're only looking at enrollment plugins where `customint1` matches AND it's a cohort sync enrollment.
Edit to add: This closes #492

MSH-492 Fix cohort-enrol course cohort sync

---

includes/functions.php

Improve version list generation by the following:
- Handles correctly 405 for the 4.5 version and 311 for 3.11 at the same time.
- Reduces generation of non-existing versions, which speeds up version-dependent command search and memory footprint.
- Function itself runs faster, even though it uses nested loops.

improve version list generation

---

Moosh/Command/Moodle39/Course/CourseEnableselfenrol.php
Moosh/Command/Moodle39/Course/CourseEnrolList.php
www/commands/index.md

Hi everyone,
First off, thanks a ton for creating this fantastic tool! I've been using it at our university and found it incredibly helpful.
I've made a couple of improvements that I'd like to contribute:
- New Options for course-enableselfenrol: Added --roleid, --name, --sendmessage, and --message options to allow for more flexible self-enrolment configuration. The previous behavior of the existing command should not be altered by the extensions.
- New Command course-enrol-list: This command lists all enrolment instances for a given course in a similar format to course-enrol-change-status, making it easier to see which methods are currently enabled or disabled.
Tested with every LTS version since 3.9. Hope you find these changes useful.

Enhance Course Enrolment Commands with Extra Options and a Listing Command

---

Moosh/Command/Moodle39/Course/CourseRestore.php
www/commands/index.md

Closes #515 
As described in the issue, this PR enables Moodle admins to provide a path to a preprocessing script for a MBZ backup. This script is run after unpacking the archive and is expected to contain a function
```php
function moosh_preprocess_mbz($path, $verbose): void
```
where `$path` represents path to a newly unpacked backup archive, which the preprocessing script can modify as needed, and `$verbose` is a verbosity flag.
The script could be provided by adding the option `--preprocess`:
```
course-restore --preprocess ./preprocessing-script.php backup_file category_id
```
This way, Moodle admins can modify the backups they are importing any way they see fit by modifying the XMLs.

Feature #515: Add course restore preprocess

---

Moosh/Command/Moodle39/Category/CategoryResortCourses.php

This defaults the subcategory sort to `name` if `shortname` or `fullname` are given as arguments; `idnumber` otherwise.
Closes #517.

MSH-517 Fix Subcategory Sorting

---

Moosh/Command/Generic/Dev/GenerateMoosh.php
Moosh/Command/Moodle39/Dev/FormAdd.php
Moosh/Command/Moodle39/Dev/GenerateFilemanager.php
Moosh/Command/Moodle39/Dev/GenerateForm.php

fixes 'Class "Twig_Loader_Filesystem" not found' error in generate-moosh

change all occurances of Twig_[Package] to \\Twig\\[Package]]

---

moosh.php

Fixes #409 
When executing `user-login` or `admin-login` commands, you may receive an HTTPS redirect notice. To fix this, we can force HTTPS in the `$_SERVER` variable. Further, if you want to get proper output with curl:
`curl -L -b 'MoodleSession:<session_id>' http://site.name/my/index.php`

user-login/admin-login: Force HTTPS to avoid redirect notice
