tmuras/moosh

Moosh/MooshCommand.php

Fix GetOptionKit printOptions usage.

---

moosh.php

Added code to check that the PHP POSIX functions are installed, and print out a sane error message if they are missing.

Added PHP POSIX Extention Test

---

Moosh/Command/Moodle23/Dev/GenerateModule.php
composer.json

Hello,
there is some important updates on the newmodule template,
like changing $module to $plugin on version.php 
=)
Kind regards,
Daniel

should use latest master for mod_newmodule template

---

Moosh/Command/Generic/Plugin/FilterSet.php

Again, life calls for a new plugin...
As I needed to set several filters system-wide on several system, I added a new plugin called "filter-set" to help me set (turn ON) those system-wide filters.
Please review and see if you can add it :-)

New plugin - Filter Set (Turn site-wide filers on/off)

---

Moosh/Command/Generic/Plugin/PluginInstall.php

fix for #140: unzip should overwrite

---

Moosh/Command/Generic/Apache/ApacheParsePerfLog.php

Also small warning when no perf info was found in given log file.

Add memcache(d) and redis to apache log parser

---

Moosh/Command/Moodle23/Category/CategoryCreate.php
Moosh/Command/Moodle23/Course/CourseCreate.php

Hi,
Thanks for your work on Moosh!
I have added an option to course-create and category-create commands to reuse existing course or category if the only course or category matches the parameters specified for command.
This option helps me to avoid unwanted duplicates when running scripts like this multiple times with some changes:
```
CATID=$(moosh category-create --visible 1 --reuse "Category 1")
COURSEID=$(moosh course-create --category $CATID --reuse "Course 1")
moosh cohort-enrol -c $COURSEID "Cohort 1"
moosh cohort-enrol -c $COURSEID "Cohort 2"
moosh cohort-enrol -c $COURSEID "Cohort 3"
```
If later I need to enroll "Cohort 4" to the same course, I can just add one more line and run the script again.

Added option to reuse existing course/category instead of creating new one

---

Moosh/Command/Moodle26/Course/CourseList.php

I had more explanation in PR #191 which I closed by mistake.

postgresql requires int to be quoted to function as boolean

---

Moosh/Command/Moodle28/Dev/GenerateGradeExport.php

Hello,
adding a missing rename here =)
Best regards!

Fix missing file rename in grade export generation

---

Moosh/Command/Moodle23/Sql/SqlCli.php

This fixes https://github.com/tmuras/moosh/issues/235

Fixes sql-cli when db-password contains special

---

Moosh/Command/Moodle31/Group/GroupAssignGrouping.php
www/commands/index.md

moosh group-assigngrouping -G groupingid groupid1 [groupid2] ...
5th of 5 group commands:
group-create, group-list, group-memberadd, grouping-create, group-assigngrouping

group-assigngrouping

---

Moosh/Command/Moodle31/Group/GroupingCreate.php
www/commands/index.md

moosh grouping-create -d "a description" -i "my id" groupingname courseid
4th of 5 group commands:
group-create, group-list, group-memberadd, grouping-create, group-assigngrouping

grouping-create

---

Moosh/Command/Moodle31/Group/GroupMemberadd.php
www/commands/index.md

moosh group-memberadd -c courseid -g groupid membername1 [membername2] ...
moosh group-memberadd -g groupid memberid1 [memberid2] ...
3rd of 5 group commands:
group-create, group-list, group-memberadd, grouping-create, group-assigngrouping

group-memberadd

---

Moosh/Command/Moodle31/Group/GroupList.php
www/commands/index.md

moosh group-list courseid ...
moosh group-list --id -G groupingid courseid
2nd of 5 group commands:
group-create, group-list, group-memberadd, grouping-create, group-assigngrouping

group-list

---

Moosh/Command/Moodle31/Group/GroupCreate.php
www/commands/index.md

First of 5 group commands:
GroupAssignGrouping.php  GroupCreate.php  GroupingCreate.php  GroupList.php  GroupMemberadd.php

group-create

---

Moosh/Command/Moodle23/Course/CourseDelete.php

Fix typo - an extra $ in variable output

Fix typo - extra $

---

Moosh/Command/Moodle36/Category/CategoryCreate.php

Just a copy of the Moodle25 one with a small deprecation fix.

add Moodle36/Category/CategoryCreate closes #257

---

Moosh/Command/Moodle36/Course/CourseList.php

3.6 version of course-list #254

---

Moosh/Command/Generic/Framework/FrameworkImport.php

Adds a command that imports a .csv competency framework with default column headers.

add Generic/Framework/FrameworkImport

---

Moosh/Command/Generic/Fontawesome/FontawesomeRefreshcache.php

Adds a command that brute force refreshes FontAwesome icon cache.

add Generic/Fontawesome/FontawesomeRefreshcache

---

Moosh/Command/Moodle36/Category/CategoryDelete.php

Should update category-delete for Moodle 3.6. Solves #273 , maybe?
Works on my 3.6 and 3.7 installs. Open to suggestions.

Fixes Issue273 - Update Category-Delete for Moodle 3.6-3.7

---

Moosh/Command/Generic/Plugin/PluginList.php
bash_completion
moosh.php

These could probably be used to improve the zsh completion stuff too, but I'm not as familiar with it.

Improve bash completion, closes #256

---

Moosh/Command/Generic/Plugin/PluginInstall.php
www/commands/index.md

Make plugin version optional for plugin-install

---

Moosh/Command/Moodle23/Block/BlockAdd.php

Fix #231 block-add course fails missing timecreated

---

Moosh/Command/Moodle25/Activity/ActivityMove.php
www/commands/index.md

Moves an activity with course_module id to end of section, or before a second activity.

activity-move

---

Moosh/Command/Moodle23/Questioncategory/QuestioncategoryCreate.php
www/commands/index.md

moosh questioncategory-create --parent 6044 --context 754 --description 清明節 --infoformat 4 --idnumber my_ID --reuse noclass

questioncategory-create

---

Moosh/Command/Moodle35/Category/CategoryList.php

Select visibilty in category-list

---

Moosh/Command/Moodle31/Role/RoleList.php
Moosh/Command/Moodle31/User/UserAssignSystemRole.php
Moosh/Command/Moodle31/User/UserUnassignSystemRole.php
www/commands/index.md

New function:
role-list
Add missing documentation for our 3 new command with examples:
role-list, user-assign-system-role, user-unassign-system-role
Add validation for system role check.

Role-list, and missing documentation

---

www/commands/index.md

course-backup: document --template and --fullbackup options

course-backup: document template and fullbackup options

---

Moosh/Command/Moodle23/User/UserCreate.php
Moosh/Command/Moodle36/Cohort/CohortEnrolfile.php
www/_site/commands/index.html
www/commands/index.md

Implements #246 - adds the --institution and --department options to user-create.

Issue246 - Add institution and department to user-create

---

Moosh/Command/Moodle35/User/ImportUserPictures.php
www/_site/commands/index.html
www/commands/index.md

Hello,
To make user-import-pictures command compliant with RGPD i've added a new policy option which check before importing a picture if the user has accepted a particular policy.
Thanks in advance for your review.
Seb

Make command compliant with RGPD with new policy option

---

composer.json
composer.lock

Fixes #393
Sorry about also updating the following:
Upgrading phpdocumentor/reflection-docblock (5.2.2 => 5.3.0)
This will fix the build process 👍

Fixes #393 - Rewrite history of Moodle to support the slave free stuff

---

Moosh/Command/Moodle39/Category/CategoryExport.php
Moosh/Command/Moodle39/Category/CategoryImport.php

Functions responsible for managing and accessing course categories are moved to class coursecat in lib/coursecatlib.php, functions responsible for rendering courses and categories lists are moved to course/renderer.php

Category export & import error

---

Moosh/Command/Moodle39/Report/DataStats.php

Remove quotes to fix compatibility with postgresql

Fix query in DataStats

---

Moosh/Command/Moodle310/Cache/CacheAddMemStore.php
Moosh/Command/Moodle33/Cache/CacheAddMemStore.php
Moosh/Command/Moodle39/Cache/CacheAddMemStore.php
www/_site/commands/index.html
www/commands/index.md

Hi,
Hope all is well.
I was hoping to make a pull request for the implementation for Adding a memcache within Moodle/Totara.
I have updated the 'index.md' and 'index.html' as well as adding three 'memcache' implementations for different versions. Following Moodle 33/39/310.
Would really appreciate the feedback on this request.
Kind Regards,
Synergy-Learning.

Added CacheAddMemStore.php for Moodle33/39/310 and updated index. Updated commands and fixed code reviews.

---

Moosh/Command/Moodle39/Cache/CacheAddMemStore.php
composer.json
includes/memcached-constants-polyfill.php

Remove Memcached dependency adding a polyfill for its constants

---

Moosh/Command/Moodle39/Dev/LabelCreate.php

Adds a label (html accepted) in a course inside a specific section with or without the completion enabled.

New command: label-create

---

Moosh/Command/Moodle39/Dev/LabelCreate.php

corrected completion short option

---

Moosh/Command/Moodle39/Group/GroupEmpty.php

Groups can be targeted by name (ilike format), idnumber (ilike format), id (=)

add a command to empty a group

---

Moosh/Command/Moodle39/Course/CourseBackup.php
Moosh/Command/Moodle39/Course/CourseRestore.php

Small update that allows you to back up a single section from a course.

Added --section option to back up single section

---

Moosh/Command/Moodle39/Course/CourseMove.php
www/commands/index.md

The code is based on the course moving section of the `bulkaction` in the `course/management.php` in Moodle.

New command: course-move

---

Moosh/Command/Moodle39/User/UserMod.php

add an option to UserMod to remove a user from global admin list

add delete-global to UserMod.php

---

Moosh/Command/Generic/Plugin/PluginHideShow.php

Hello,
please find a correction for block hide show parameter check
Regards
Céline

correct block hide show value parameter check

---

Moosh/Command/Moodle33/Role/RoleExport.php

Fix for #527 
To allow stdout export again

#527 - Allow role-export to stdout again
